---
title: 'Model call record'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: September 2020
---

Calculates emission factors

Check package version.

```{r}
packageVersion('ALFAM2')
```

Parameter values.

```{r}
ALFAM2pars02
dat
```

Run model 

With set 2 parameters

```{r}
preds <- ALFAM2mod(dat, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', time.incorp = 't.incorp', group = 'id', warn = TRUE)
digpreds <- ALFAM2mod(digdat, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', time.incorp = 't.incorp', group = 'id', warn = TRUE)
```

Check reference condition.

```{r}
ALFAM2mod(ref, pars = ALFAM2pars01, app.name = 'tan.app', time.name = 'ct', time.incorp = 't.incorp', warn = TRUE)
ALFAM2mod(ref, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', time.incorp = 't.incorp', warn = TRUE)
```

Add results to main df
```{r}
#dat$EF <- signif(preds$er, 2)
dat$EF <- preds$er
dat$EFp <- 100 * signif(preds$er, 2)
```

```{r}
digdat$EF <- digpreds$er
```


