---
title: 'Stats'
output: pdf_document
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

# LF vs. RS effect

Generates results for this statement:

```
In general, a clear reduction in the emission factors after application 
of the liquid fraction was found relative to application of the raw 
slurry (Figure 2) (p < 1·10-8 from F-test based on 2-factor ANOVA) . 
```

```{r}
dd <- subset(dat, frac.stud != 'mix')

mod <- lm(log10(EFp.field) ~ frac.stud.nm + interaction(source, set), data = dd)
anova(mod)
coef(mod)[1:3]
100 * (10^coef(mod)[1:3] - 1)
```

```{r}
mod <- lm(log10(EFp.field) ~ DM, data = dd)
anova(mod)
summary(mod)
```

# Compare EF vs. DM slopes for measurements and ALFAM2 predictions

Comparison for this statement: 

```
The average EFemission factors vs. DM slope from literature data is 3.3 
(95% CI: 2.1, 4.6) vs. 4.6 for model predictions 
(units are % applied TAN per % of fresh mass).
```

CI on slope for measurements.

```{r}
ggplot(dat, aes(man.dm, EFp.field, colour = man.source)) + geom_point() + facet_wrap(~ source)
```

```{r}
cc <- plyr::ddply(dat, c('source', 'set', 'man.source'), function(x) coef(lm(EFp.field ~ man.dm, data = x))[2])
t.test(cc$man.dm[cc$man.source == 'Cattle'])
t.test(cc$man.dm[cc$man.source == 'Pig'])
t.test(cc$man.dm[cc$man.source == 'Digestate'])
t.test(cc$man.dm)
range(cc$man.dm)
median(cc$man.dm)
mean(cc$man.dm)
```

Model slope.

```{r}
ggplot(a2dat, aes(man.dm, EFp.field, colour = man.source)) + geom_point() 
```

```{r}
mod2b <- lm(EFp.field ~ man.dm, data = a2dat)
summary(mod2b)
```

