---
title: Understanding ALFAM2 pH response
author: Sasha D. Hafner
output: pdf_document
date: January 2021
---

```{r}
rm(list = ls())
library(ALFAM2)
library(ggplot2)
library(dplyr)
source('../../functions/rounddf.R')
```

Get, tweak pars

```{r}
load('../../parameters/parf.RData')
pars <- parf
pars['man.ph.r1'] <- 0.66
pars['man.ph.r3'] <- 0.24
```

Input data.

```{r}
dat <- data.frame(ct = 168, 
                  man.ph = 90:50/10,
                  TAN.app = 100)
dat$id <- 1:nrow(dat)
```

Run model.

```{r}
pred <- ALFAM2mod(dat, pars = pars, group = 'id')
dat <- cbind(dat, pred[, -1:-3])
head(dat)
dat$red0.5 <- c(dat$er[1:(nrow(dat) - 10)] - dat$er[-1:-10], rep(NA, 10))
dat$rred0.5 <- 100 * dat$red0.5 / dat$er
```

Plot.

```{r}

ggplot(dat, aes(man.ph, er)) +
  geom_line() +
  labs(x = 'pH', y = 'Relative emission (% of TAN)')

ggplot(dat, aes(man.ph, red0.5)) +
  geom_line() +
  labs(x = 'Initial pH', y = 'Reduction w 0.5 unit decrease (% TAN)')

ggplot(dat, aes(man.ph, rred0.5)) +
  geom_line() +
  labs(x = 'Initial pH', y = 'Relative reduction w 0.5 unit decrease (% untreated emis.)')

```
