---
title: 'Model call record'
output: pdf_document
classoption: landscape
author: Sasha D. Hafner
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

Calculates emission factors

Check package version.

```{r}
packageVersion('ALFAM2')
```

Parameter values.

```{r}
ALFAM2pars02
```

Run model 

With set 2 parameters

```{r}
refpreds <- alfam2(refdat, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', group = 'id', warn = TRUE, prep = TRUE)
lfpreds <- alfam2(lfdat, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', group = 'id', warn = TRUE, prep = TRUE)
sfpreds <- alfam2(sfdat, pars = ALFAM2pars02, app.name = 'tan.app', time.name = 'ct', 
                     time.incorp = 't.incorp', group = 'id', warn = TRUE, prep = TRUE)
```

Add results to main df for calculating overall EFs
```{r}
refdat$EF.field <- signif(refpreds$er, 4)
lfdat$EF.field <- signif(lfpreds$er, 4)
sfdat$EF.field <- signif(sfpreds$er, 4)
```

Check size of data frames

```{r}
dim(refdat)
dim(lfdat)
dim(sfdat)

table(lfdat$man.source, lfdat$scenario, lfdat$app.mthd, lfdat$app.timing)
table(sfdat$man.source, sfdat$scenario, sfdat$app.mthd, sfdat$app.timing)
```

